name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  
jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger l'artefact de succès pour API
        uses: actions/download-artifact@v4
        with:
          name: lint-and-build-success
        if: ${{ github.event.workflow_run.name == 'Lint API' }}

      - name: Télécharger l'artefact de succès pour WebSocket
        uses: actions/download-artifact@v4
        with:
          name: websocket-lint-and-build-success
        if: ${{ github.event.workflow_run.name == 'Lint WebSocket' }}

      - name: Télécharger l'artefact de succès pour Frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-lint-and-build-success
        if: ${{ github.event.workflow_run.name == 'Lint and Build Frontend' }}

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME || 'default-username' }}
          password: ${{ secrets.DOCKER_PASSWORD || 'default-password' }}

      - name: Définir la version basée sur le numéro de build GitHub
        id: version
        run: echo "VERSION=${{ github.run_number || '1' }}" >> $GITHUB_ENV

      - name: Build et push de l'image API
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-api:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-api:latest ./packages/api
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-api:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-api:latest

      - name: Build et push de l'image WebSocket
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-websocket:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-websocket:latest ./packages/websocket
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-websocket:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-websocket:latest

      - name: Build et push de l'image Frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --build-arg VITE_WS_URL=${{ secrets.VITE_WS_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-frontend:${{ env.VERSION }} \
            -t ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-frontend:latest \
            ./packages/client
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-frontend:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelnoriginality-frontend:latest
          
      - name: Créer un marqueur de succès pour le build Docker
        run: echo "DOCKER_SUCCESS=true" > docker_success.txt
        
      - name: Sauvegarder le résultat du build Docker
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-success
          path: docker_success.txt

  deploy:
    name: Déploiement sur la VM
    needs: docker
    runs-on: ubuntu-latest
    if: ${{ needs.docker.result == 'success' }}

    steps:
      - name: Attendre que le job Docker soit terminé avec succès
        run: echo "Le job Docker s'est terminé avec succès. Début du déploiement."
          
      - name: Télécharger le résultat du build Docker
        uses: actions/download-artifact@v4
        with:
          name: docker-build-success
          
      - name: Vérifier les résultats précédents
        run: |
          if [[ ! -f docker_success.txt ]]; then
            echo "Les étapes précédentes n'ont pas toutes réussi. Arrêt du déploiement."
            exit 1
          fi
    
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installer SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY || '' }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST || 'default-host' }} >> ~/.ssh/known_hosts

      - name: Copier le fichier docker-compose sur la VM
        run: |
          scp -i ~/.ssh/id_rsa ./docker-compose.yml ${{ secrets.SSH_USER || 'default-user' }}@${{ secrets.VM_HOST || 'default-host' }}:~/docker-compose.yml

      - name: Créer le fichier .env.backend sur la VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "cat > ~/.env.backend << 'EOL'
          ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
          MONGO_URL=${{ secrets.MONGO_URL }}
          INIT_SECRET_KEY=${{ secrets.INIT_SECRET_KEY }}
          EOL"

      - name: Déployer et lancer le docker-compose
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "cd ~ && \
          docker-compose pull && \
          docker-compose down && \
          docker-compose up --build -d"

      - name: Vérifier le statut des conteneurs
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "docker-compose ps"
          
      - name: Nettoyer la clé SSH
        run: |
          rm -f ~/.ssh/id_rsa
        if: always()