name: Build React App

on:
  push:
    paths:
      - "packages/client/**"
  pull_request:
    paths:
      - "packages/client/**"

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Installation des dépendances
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint --workspace=client

      - name: Build
        run: |
          npm run build --workspace=client
