name: Lint WebSocket

on:
  pull_request:

jobs:
  build:
    name: Lint WebSocket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Installation des dépendances
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint --workspace=websocket

      - name: Créer un artefact de succès
        uses: actions/upload-artifact@v4
        with:
          name: websocket-lint-and-build-success
          path: success.txt